// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PartWindowParam.proto

#ifndef PROTOBUF_PartWindowParam_2eproto__INCLUDED
#define PROTOBUF_PartWindowParam_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_PartWindowParam_2eproto();
void protobuf_AssignDesc_PartWindowParam_2eproto();
void protobuf_ShutdownFile_PartWindowParam_2eproto();

class PartWindowParam;
class PartWindowParam_PartParam;

// ===================================================================

class PartWindowParam_PartParam : public ::google::protobuf::Message {
 public:
  PartWindowParam_PartParam();
  virtual ~PartWindowParam_PartParam();
  
  PartWindowParam_PartParam(const PartWindowParam_PartParam& from);
  
  inline PartWindowParam_PartParam& operator=(const PartWindowParam_PartParam& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const PartWindowParam_PartParam& default_instance();
  
  void Swap(PartWindowParam_PartParam* other);
  
  // implements Message ----------------------------------------------
  
  PartWindowParam_PartParam* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PartWindowParam_PartParam& from);
  void MergeFrom(const PartWindowParam_PartParam& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 part_id = 6;
  inline bool has_part_id() const;
  inline void clear_part_id();
  static const int kPartIdFieldNumber = 6;
  inline ::google::protobuf::int32 part_id() const;
  inline void set_part_id(::google::protobuf::int32 value);
  
  // optional int32 type_id = 11;
  inline bool has_type_id() const;
  inline void clear_type_id();
  static const int kTypeIdFieldNumber = 11;
  inline ::google::protobuf::int32 type_id() const;
  inline void set_type_id(::google::protobuf::int32 value);
  
  // optional int32 window_size_x = 1 [default = 0];
  inline bool has_window_size_x() const;
  inline void clear_window_size_x();
  static const int kWindowSizeXFieldNumber = 1;
  inline ::google::protobuf::int32 window_size_x() const;
  inline void set_window_size_x(::google::protobuf::int32 value);
  
  // optional int32 window_size_y = 2 [default = 0];
  inline bool has_window_size_y() const;
  inline void clear_window_size_y();
  static const int kWindowSizeYFieldNumber = 2;
  inline ::google::protobuf::int32 window_size_y() const;
  inline void set_window_size_y(::google::protobuf::int32 value);
  
  // optional int32 pos_offset_x = 3;
  inline bool has_pos_offset_x() const;
  inline void clear_pos_offset_x();
  static const int kPosOffsetXFieldNumber = 3;
  inline ::google::protobuf::int32 pos_offset_x() const;
  inline void set_pos_offset_x(::google::protobuf::int32 value);
  
  // optional int32 pos_offset_y = 4;
  inline bool has_pos_offset_y() const;
  inline void clear_pos_offset_y();
  static const int kPosOffsetYFieldNumber = 4;
  inline ::google::protobuf::int32 pos_offset_y() const;
  inline void set_pos_offset_y(::google::protobuf::int32 value);
  
  // optional int32 root_offset_x = 13;
  inline bool has_root_offset_x() const;
  inline void clear_root_offset_x();
  static const int kRootOffsetXFieldNumber = 13;
  inline ::google::protobuf::int32 root_offset_x() const;
  inline void set_root_offset_x(::google::protobuf::int32 value);
  
  // optional int32 root_offset_y = 14;
  inline bool has_root_offset_y() const;
  inline void clear_root_offset_y();
  static const int kRootOffsetYFieldNumber = 14;
  inline ::google::protobuf::int32 root_offset_y() const;
  inline void set_root_offset_y(::google::protobuf::int32 value);
  
  // optional float root_rot = 15;
  inline bool has_root_rot() const;
  inline void clear_root_rot();
  static const int kRootRotFieldNumber = 15;
  inline float root_rot() const;
  inline void set_root_rot(float value);
  
  // @@protoc_insertion_point(class_scope:PartWindowParam.PartParam)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::int32 part_id_;
  ::google::protobuf::int32 type_id_;
  ::google::protobuf::int32 window_size_x_;
  ::google::protobuf::int32 window_size_y_;
  ::google::protobuf::int32 pos_offset_x_;
  ::google::protobuf::int32 pos_offset_y_;
  ::google::protobuf::int32 root_offset_x_;
  ::google::protobuf::int32 root_offset_y_;
  float root_rot_;
  friend void  protobuf_AddDesc_PartWindowParam_2eproto();
  friend void protobuf_AssignDesc_PartWindowParam_2eproto();
  friend void protobuf_ShutdownFile_PartWindowParam_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(9 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static PartWindowParam_PartParam* default_instance_;
};
// -------------------------------------------------------------------

class PartWindowParam : public ::google::protobuf::Message {
 public:
  PartWindowParam();
  virtual ~PartWindowParam();
  
  PartWindowParam(const PartWindowParam& from);
  
  inline PartWindowParam& operator=(const PartWindowParam& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const PartWindowParam& default_instance();
  
  void Swap(PartWindowParam* other);
  
  // implements Message ----------------------------------------------
  
  PartWindowParam* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PartWindowParam& from);
  void MergeFrom(const PartWindowParam& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef PartWindowParam_PartParam PartParam;
  
  // accessors -------------------------------------------------------
  
  // repeated .PartWindowParam.PartParam part = 5;
  inline int part_size() const;
  inline void clear_part();
  static const int kPartFieldNumber = 5;
  inline const ::PartWindowParam_PartParam& part(int index) const;
  inline ::PartWindowParam_PartParam* mutable_part(int index);
  inline ::PartWindowParam_PartParam* add_part();
  inline const ::google::protobuf::RepeatedPtrField< ::PartWindowParam_PartParam >&
      part() const;
  inline ::google::protobuf::RepeatedPtrField< ::PartWindowParam_PartParam >*
      mutable_part();
  
  // optional double train_object_height = 7 [default = 200];
  inline bool has_train_object_height() const;
  inline void clear_train_object_height();
  static const int kTrainObjectHeightFieldNumber = 7;
  inline double train_object_height() const;
  inline void set_train_object_height(double value);
  
  // optional double bbox_offset_x = 9 [default = 0];
  inline bool has_bbox_offset_x() const;
  inline void clear_bbox_offset_x();
  static const int kBboxOffsetXFieldNumber = 9;
  inline double bbox_offset_x() const;
  inline void set_bbox_offset_x(double value);
  
  // optional double bbox_offset_y = 10 [default = 0];
  inline bool has_bbox_offset_y() const;
  inline void clear_bbox_offset_y();
  static const int kBboxOffsetYFieldNumber = 10;
  inline double bbox_offset_y() const;
  inline void set_bbox_offset_y(double value);
  
  // @@protoc_insertion_point(class_scope:PartWindowParam)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::RepeatedPtrField< ::PartWindowParam_PartParam > part_;
  double train_object_height_;
  double bbox_offset_x_;
  double bbox_offset_y_;
  friend void  protobuf_AddDesc_PartWindowParam_2eproto();
  friend void protobuf_AssignDesc_PartWindowParam_2eproto();
  friend void protobuf_ShutdownFile_PartWindowParam_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static PartWindowParam* default_instance_;
};
// ===================================================================


// ===================================================================

// PartWindowParam_PartParam

// optional int32 part_id = 6;
inline bool PartWindowParam_PartParam::has_part_id() const {
  return _has_bit(0);
}
inline void PartWindowParam_PartParam::clear_part_id() {
  part_id_ = 0;
  _clear_bit(0);
}
inline ::google::protobuf::int32 PartWindowParam_PartParam::part_id() const {
  return part_id_;
}
inline void PartWindowParam_PartParam::set_part_id(::google::protobuf::int32 value) {
  _set_bit(0);
  part_id_ = value;
}

// optional int32 type_id = 11;
inline bool PartWindowParam_PartParam::has_type_id() const {
  return _has_bit(1);
}
inline void PartWindowParam_PartParam::clear_type_id() {
  type_id_ = 0;
  _clear_bit(1);
}
inline ::google::protobuf::int32 PartWindowParam_PartParam::type_id() const {
  return type_id_;
}
inline void PartWindowParam_PartParam::set_type_id(::google::protobuf::int32 value) {
  _set_bit(1);
  type_id_ = value;
}

// optional int32 window_size_x = 1 [default = 0];
inline bool PartWindowParam_PartParam::has_window_size_x() const {
  return _has_bit(2);
}
inline void PartWindowParam_PartParam::clear_window_size_x() {
  window_size_x_ = 0;
  _clear_bit(2);
}
inline ::google::protobuf::int32 PartWindowParam_PartParam::window_size_x() const {
  return window_size_x_;
}
inline void PartWindowParam_PartParam::set_window_size_x(::google::protobuf::int32 value) {
  _set_bit(2);
  window_size_x_ = value;
}

// optional int32 window_size_y = 2 [default = 0];
inline bool PartWindowParam_PartParam::has_window_size_y() const {
  return _has_bit(3);
}
inline void PartWindowParam_PartParam::clear_window_size_y() {
  window_size_y_ = 0;
  _clear_bit(3);
}
inline ::google::protobuf::int32 PartWindowParam_PartParam::window_size_y() const {
  return window_size_y_;
}
inline void PartWindowParam_PartParam::set_window_size_y(::google::protobuf::int32 value) {
  _set_bit(3);
  window_size_y_ = value;
}

// optional int32 pos_offset_x = 3;
inline bool PartWindowParam_PartParam::has_pos_offset_x() const {
  return _has_bit(4);
}
inline void PartWindowParam_PartParam::clear_pos_offset_x() {
  pos_offset_x_ = 0;
  _clear_bit(4);
}
inline ::google::protobuf::int32 PartWindowParam_PartParam::pos_offset_x() const {
  return pos_offset_x_;
}
inline void PartWindowParam_PartParam::set_pos_offset_x(::google::protobuf::int32 value) {
  _set_bit(4);
  pos_offset_x_ = value;
}

// optional int32 pos_offset_y = 4;
inline bool PartWindowParam_PartParam::has_pos_offset_y() const {
  return _has_bit(5);
}
inline void PartWindowParam_PartParam::clear_pos_offset_y() {
  pos_offset_y_ = 0;
  _clear_bit(5);
}
inline ::google::protobuf::int32 PartWindowParam_PartParam::pos_offset_y() const {
  return pos_offset_y_;
}
inline void PartWindowParam_PartParam::set_pos_offset_y(::google::protobuf::int32 value) {
  _set_bit(5);
  pos_offset_y_ = value;
}

// optional int32 root_offset_x = 13;
inline bool PartWindowParam_PartParam::has_root_offset_x() const {
  return _has_bit(6);
}
inline void PartWindowParam_PartParam::clear_root_offset_x() {
  root_offset_x_ = 0;
  _clear_bit(6);
}
inline ::google::protobuf::int32 PartWindowParam_PartParam::root_offset_x() const {
  return root_offset_x_;
}
inline void PartWindowParam_PartParam::set_root_offset_x(::google::protobuf::int32 value) {
  _set_bit(6);
  root_offset_x_ = value;
}

// optional int32 root_offset_y = 14;
inline bool PartWindowParam_PartParam::has_root_offset_y() const {
  return _has_bit(7);
}
inline void PartWindowParam_PartParam::clear_root_offset_y() {
  root_offset_y_ = 0;
  _clear_bit(7);
}
inline ::google::protobuf::int32 PartWindowParam_PartParam::root_offset_y() const {
  return root_offset_y_;
}
inline void PartWindowParam_PartParam::set_root_offset_y(::google::protobuf::int32 value) {
  _set_bit(7);
  root_offset_y_ = value;
}

// optional float root_rot = 15;
inline bool PartWindowParam_PartParam::has_root_rot() const {
  return _has_bit(8);
}
inline void PartWindowParam_PartParam::clear_root_rot() {
  root_rot_ = 0;
  _clear_bit(8);
}
inline float PartWindowParam_PartParam::root_rot() const {
  return root_rot_;
}
inline void PartWindowParam_PartParam::set_root_rot(float value) {
  _set_bit(8);
  root_rot_ = value;
}

// -------------------------------------------------------------------

// PartWindowParam

// repeated .PartWindowParam.PartParam part = 5;
inline int PartWindowParam::part_size() const {
  return part_.size();
}
inline void PartWindowParam::clear_part() {
  part_.Clear();
}
inline const ::PartWindowParam_PartParam& PartWindowParam::part(int index) const {
  return part_.Get(index);
}
inline ::PartWindowParam_PartParam* PartWindowParam::mutable_part(int index) {
  return part_.Mutable(index);
}
inline ::PartWindowParam_PartParam* PartWindowParam::add_part() {
  return part_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::PartWindowParam_PartParam >&
PartWindowParam::part() const {
  return part_;
}
inline ::google::protobuf::RepeatedPtrField< ::PartWindowParam_PartParam >*
PartWindowParam::mutable_part() {
  return &part_;
}

// optional double train_object_height = 7 [default = 200];
inline bool PartWindowParam::has_train_object_height() const {
  return _has_bit(1);
}
inline void PartWindowParam::clear_train_object_height() {
  train_object_height_ = 200;
  _clear_bit(1);
}
inline double PartWindowParam::train_object_height() const {
  return train_object_height_;
}
inline void PartWindowParam::set_train_object_height(double value) {
  _set_bit(1);
  train_object_height_ = value;
}

// optional double bbox_offset_x = 9 [default = 0];
inline bool PartWindowParam::has_bbox_offset_x() const {
  return _has_bit(2);
}
inline void PartWindowParam::clear_bbox_offset_x() {
  bbox_offset_x_ = 0;
  _clear_bit(2);
}
inline double PartWindowParam::bbox_offset_x() const {
  return bbox_offset_x_;
}
inline void PartWindowParam::set_bbox_offset_x(double value) {
  _set_bit(2);
  bbox_offset_x_ = value;
}

// optional double bbox_offset_y = 10 [default = 0];
inline bool PartWindowParam::has_bbox_offset_y() const {
  return _has_bit(3);
}
inline void PartWindowParam::clear_bbox_offset_y() {
  bbox_offset_y_ = 0;
  _clear_bit(3);
}
inline double PartWindowParam::bbox_offset_y() const {
  return bbox_offset_y_;
}
inline void PartWindowParam::set_bbox_offset_y(double value) {
  _set_bit(3);
  bbox_offset_y_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_PartWindowParam_2eproto__INCLUDED
