/*
 * @(#)mcr.h    generated by: makeheader 5.1.5  Mon Aug  4 18:05:12 2008
 *
 *		built from:	../../src/include/copyright.h
 *				../../src/include/pragma_interface.h
 *				runtime/CompilerSink.cpp
 *				runtime/CompilerStreamBuffer.cpp
 *				runtime/DepfunRules.cpp
 *				runtime/StdCmdWinSink.cpp
 *				runtime/context.cpp
 *				runtime/depfun.cpp
 *				runtime/emergency_exit.cpp
 *				runtime/initterm.cpp
 *				runtime/lmgrsup.cpp
 *				runtime/lmgrsup_mac.cpp
 *				runtime/loginout.cpp
 *				runtime/mwassert.cpp
 *				runtime/runtime.cpp
 *				runtime/runtime_mac.cpp
 *				runtime/shield.cpp
 *				runtime/shutdown.cpp
 *				runtime/sighndl.cpp
 */

#if defined(_MSC_VER) || __GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ > 3)
#pragma once
#endif

#ifndef mcr_h
#define mcr_h


/*
 * Copyright 1984-2003 The MathWorks, Inc.
 * All Rights Reserved.
 */



/* Copyright 2003-2006 The MathWorks, Inc. */

/* Only define EXTERN_C if it hasn't been defined already. This allows
 * individual modules to have more control over managing their exports.
 */
#ifndef EXTERN_C

#ifdef __cplusplus
  #define EXTERN_C extern "C"
#else
  #define EXTERN_C extern
#endif

#endif

#endif /* mcr_h */
