// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HypothesisList.proto

#ifndef PROTOBUF_HypothesisList_2eproto__INCLUDED
#define PROTOBUF_HypothesisList_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_HypothesisList_2eproto();
void protobuf_AssignDesc_HypothesisList_2eproto();
void protobuf_ShutdownFile_HypothesisList_2eproto();

class HypothesisList;
class HypothesisList_ObjectHypothesis;

// ===================================================================

class HypothesisList_ObjectHypothesis : public ::google::protobuf::Message {
 public:
  HypothesisList_ObjectHypothesis();
  virtual ~HypothesisList_ObjectHypothesis();
  
  HypothesisList_ObjectHypothesis(const HypothesisList_ObjectHypothesis& from);
  
  inline HypothesisList_ObjectHypothesis& operator=(const HypothesisList_ObjectHypothesis& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const HypothesisList_ObjectHypothesis& default_instance();
  
  void Swap(HypothesisList_ObjectHypothesis* other);
  
  // implements Message ----------------------------------------------
  
  HypothesisList_ObjectHypothesis* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HypothesisList_ObjectHypothesis& from);
  void MergeFrom(const HypothesisList_ObjectHypothesis& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional float x = 1;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 1;
  inline float x() const;
  inline void set_x(float value);
  
  // optional float y = 2;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 2;
  inline float y() const;
  inline void set_y(float value);
  
  // optional float scale = 3;
  inline bool has_scale() const;
  inline void clear_scale();
  static const int kScaleFieldNumber = 3;
  inline float scale() const;
  inline void set_scale(float value);
  
  // optional float score = 4;
  inline bool has_score() const;
  inline void clear_score();
  static const int kScoreFieldNumber = 4;
  inline float score() const;
  inline void set_score(float value);
  
  // optional bool flip = 5 [default = false];
  inline bool has_flip() const;
  inline void clear_flip();
  static const int kFlipFieldNumber = 5;
  inline bool flip() const;
  inline void set_flip(bool value);
  
  // @@protoc_insertion_point(class_scope:HypothesisList.ObjectHypothesis)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  float x_;
  float y_;
  float scale_;
  float score_;
  bool flip_;
  friend void  protobuf_AddDesc_HypothesisList_2eproto();
  friend void protobuf_AssignDesc_HypothesisList_2eproto();
  friend void protobuf_ShutdownFile_HypothesisList_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static HypothesisList_ObjectHypothesis* default_instance_;
};
// -------------------------------------------------------------------

class HypothesisList : public ::google::protobuf::Message {
 public:
  HypothesisList();
  virtual ~HypothesisList();
  
  HypothesisList(const HypothesisList& from);
  
  inline HypothesisList& operator=(const HypothesisList& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const HypothesisList& default_instance();
  
  void Swap(HypothesisList* other);
  
  // implements Message ----------------------------------------------
  
  HypothesisList* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HypothesisList& from);
  void MergeFrom(const HypothesisList& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef HypothesisList_ObjectHypothesis ObjectHypothesis;
  
  // accessors -------------------------------------------------------
  
  // repeated .HypothesisList.ObjectHypothesis hyp = 1;
  inline int hyp_size() const;
  inline void clear_hyp();
  static const int kHypFieldNumber = 1;
  inline const ::HypothesisList_ObjectHypothesis& hyp(int index) const;
  inline ::HypothesisList_ObjectHypothesis* mutable_hyp(int index);
  inline ::HypothesisList_ObjectHypothesis* add_hyp();
  inline const ::google::protobuf::RepeatedPtrField< ::HypothesisList_ObjectHypothesis >&
      hyp() const;
  inline ::google::protobuf::RepeatedPtrField< ::HypothesisList_ObjectHypothesis >*
      mutable_hyp();
  
  // @@protoc_insertion_point(class_scope:HypothesisList)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::RepeatedPtrField< ::HypothesisList_ObjectHypothesis > hyp_;
  friend void  protobuf_AddDesc_HypothesisList_2eproto();
  friend void protobuf_AssignDesc_HypothesisList_2eproto();
  friend void protobuf_ShutdownFile_HypothesisList_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static HypothesisList* default_instance_;
};
// ===================================================================


// ===================================================================

// HypothesisList_ObjectHypothesis

// optional float x = 1;
inline bool HypothesisList_ObjectHypothesis::has_x() const {
  return _has_bit(0);
}
inline void HypothesisList_ObjectHypothesis::clear_x() {
  x_ = 0;
  _clear_bit(0);
}
inline float HypothesisList_ObjectHypothesis::x() const {
  return x_;
}
inline void HypothesisList_ObjectHypothesis::set_x(float value) {
  _set_bit(0);
  x_ = value;
}

// optional float y = 2;
inline bool HypothesisList_ObjectHypothesis::has_y() const {
  return _has_bit(1);
}
inline void HypothesisList_ObjectHypothesis::clear_y() {
  y_ = 0;
  _clear_bit(1);
}
inline float HypothesisList_ObjectHypothesis::y() const {
  return y_;
}
inline void HypothesisList_ObjectHypothesis::set_y(float value) {
  _set_bit(1);
  y_ = value;
}

// optional float scale = 3;
inline bool HypothesisList_ObjectHypothesis::has_scale() const {
  return _has_bit(2);
}
inline void HypothesisList_ObjectHypothesis::clear_scale() {
  scale_ = 0;
  _clear_bit(2);
}
inline float HypothesisList_ObjectHypothesis::scale() const {
  return scale_;
}
inline void HypothesisList_ObjectHypothesis::set_scale(float value) {
  _set_bit(2);
  scale_ = value;
}

// optional float score = 4;
inline bool HypothesisList_ObjectHypothesis::has_score() const {
  return _has_bit(3);
}
inline void HypothesisList_ObjectHypothesis::clear_score() {
  score_ = 0;
  _clear_bit(3);
}
inline float HypothesisList_ObjectHypothesis::score() const {
  return score_;
}
inline void HypothesisList_ObjectHypothesis::set_score(float value) {
  _set_bit(3);
  score_ = value;
}

// optional bool flip = 5 [default = false];
inline bool HypothesisList_ObjectHypothesis::has_flip() const {
  return _has_bit(4);
}
inline void HypothesisList_ObjectHypothesis::clear_flip() {
  flip_ = false;
  _clear_bit(4);
}
inline bool HypothesisList_ObjectHypothesis::flip() const {
  return flip_;
}
inline void HypothesisList_ObjectHypothesis::set_flip(bool value) {
  _set_bit(4);
  flip_ = value;
}

// -------------------------------------------------------------------

// HypothesisList

// repeated .HypothesisList.ObjectHypothesis hyp = 1;
inline int HypothesisList::hyp_size() const {
  return hyp_.size();
}
inline void HypothesisList::clear_hyp() {
  hyp_.Clear();
}
inline const ::HypothesisList_ObjectHypothesis& HypothesisList::hyp(int index) const {
  return hyp_.Get(index);
}
inline ::HypothesisList_ObjectHypothesis* HypothesisList::mutable_hyp(int index) {
  return hyp_.Mutable(index);
}
inline ::HypothesisList_ObjectHypothesis* HypothesisList::add_hyp() {
  return hyp_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::HypothesisList_ObjectHypothesis >&
HypothesisList::hyp() const {
  return hyp_;
}
inline ::google::protobuf::RepeatedPtrField< ::HypothesisList_ObjectHypothesis >*
HypothesisList::mutable_hyp() {
  return &hyp_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_HypothesisList_2eproto__INCLUDED
